deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
  - key: api.openshift.com/id
    operator: In
    values: ["1g268u7pp694gj152nj16me4sv615lpv"]  # any Hive integration cluster IDs
  - key: ext-managed.openshift.io/hive-shard
    operator: In
    values: ["true"]
